insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Friedrichstraﬂe', '54', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Friedrichstraﬂe', '18', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Friedrichstraﬂe', '101', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Friedrichstraﬂe', '154', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Seigerh¸ttenweg', '1', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Seigerh¸ttenweg', '15', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Seigerh¸ttenweg', '72', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Seigerh¸ttenweg', '43', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Seigerh¸ttenweg', '53', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'An der Holtemme', '19', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'An der Holtemme', '21a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedter Weg', '125', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Minslebenderstraﬂe', '43', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Minslebenderstraﬂe', '71', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Minslebenderstraﬂe', '9', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Minslebenderstraﬂe', '7', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Albert-Bartels-Straﬂe', '4', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Albert-Bartels-Straﬂe', '41', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Albert-Bartels-Straﬂe', '73', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Albert-Bartels-Straﬂe', '31', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ringstraﬂe', '34', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ringstraﬂe', '59', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ringstraﬂe', '101a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Charlottenlust', '104', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Charlottenlust', '64b', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Charlottenlust', '3', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ilsenburger-Straﬂe', '132', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ilsenburger-Straﬂe', '11', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ilsenburger-Straﬂe', '73', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ilsenburger-Straﬂe', '3a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ilsenburger-Straﬂe', '54b', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Burgm¸hlenstraﬂe', '13d', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Burgm¸hlenstraﬂe', '6', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Papental', '13b', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Burgstraﬂe', '18c', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Burgstraﬂe', '8a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Burgstraﬂe', '72', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Karl-Marx-Straﬂe', '10a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Karl-Marx-Straﬂe', '17', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Karl-Marx-Straﬂe', '71b', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Karl-Marx-Straﬂe', '47', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Quittengrund', '12', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'An der Tongrube', '52', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'An der Tongrube', '27c', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'An der Tongrube', '110', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'An der Tongrube', '27a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hundertmorgenfeld', '52', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hundertmorgenfeld', '51a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hundertmorgenfeld', '14', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hundertmorgenfeld', '2', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Gieﬂerweg', '62', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Gieﬂerweg', '81', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Gieﬂerweg', '49', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedterweg', '63a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedterweg', '63b', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedterweg', '22', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedterweg', '19', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedterweg', '11', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedterweg', '15a', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Veckenstedterweg', '37', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Heinrich-Heine-Straﬂe', '51', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Heinrich-Heine-Straﬂe', '71', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Heinrich-Heine-Straﬂe', '42', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Heinrich-Heine-Straﬂe', '91', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Mˆnchstieg', '95', 38855, 'Wernigerode', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Mˆnchstieg', '63a', 38855, 'Wernigerode', 'Deutschland');

commit;

insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Elbestraﬂe', '83', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Elbestraﬂe', '15', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Elbestraﬂe', '72b', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Elbestraﬂe', '43a', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Elbestraﬂe', '103', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '99', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '11', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '19', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '77a', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '43b', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '51', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '9', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '42', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '13', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Lichtenbergerstraﬂe', '91', 38120, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '43', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '19', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '100', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '11', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '15b', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '72ab', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '43b', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '51', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '98', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '61', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Bevenroderstraﬂe', '51', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Peterskamp', '79', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Peterskamp', '47', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Peterskamp', '59a', 38108, 'Braunschweig', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Peterskamp', '101', 38108, 'Braunschweig', 'Deutschland');

commit;

insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hagebuttenweg', '21', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hagebuttenweg', '3', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hagebuttenweg', '10', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Hagebuttenweg', '9a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Haselweg', '101', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Haselweg', '77', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Haselweg', '4a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Haselweg', '12a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ginsterweg', '9a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ginsterweg', '91', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Ginsterweg', '11', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Holunderweg', '33', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Holunderweg', '13', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Holunderweg', '9d', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Holunderweg', '1a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Holunderweg', '7b', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Brombeerweg', '49', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Brombeerweg', '3', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Brombeerweg', '59d', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Brombeerweg', '102', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Brombeerweg', '7d', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'S¸dstraﬂe', '91', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'S¸dstraﬂe', '83', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'S¸dstraﬂe', '66', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'S¸dstraﬂe', '11', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Mozartstraﬂe', '73', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Mozartstraﬂe', '41a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Mozartstraﬂe', '101', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Mozartstraﬂe', '59', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Mozartstraﬂe', '11d', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '1b', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '3a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '103', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '59a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '51', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '79', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '44a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Beethovenstraﬂe', '13', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Pappelweg', '59a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Pappelweg', '101a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Pappelweg', '99', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Pappelweg', '41a', 38820, 'Halberstadt', 'Deutschland');
insert into ADDRESS values(ADDRESSIDSEQ.nextval, 'Pappelweg', '13', 38820, 'Halberstadt', 'Deutschland');

commit;