INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Paypal', 0.35);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Lastschrift', 0);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Vorkasse', 0);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Rechnung', 1.50);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Kreditkarte', 0.5);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Nachnahme', 5);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Sofortueberweisung', 1.20);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Klarna', 0);
INSERT INTO PAYMETHOD VALUES (PAYMETHODIDSEQ.nextval, 'Giropay', 0);

select * from paymethod;

commit;

INSERT INTO PAYMETHOD VALUES ('Paypal');
INSERT INTO PAYMETHOD VALUES ('Lastschrift');
INSERT INTO PAYMETHOD VALUES ('Vorkasse');
INSERT INTO PAYMETHOD VALUES ('Rechnung');
INSERT INTO PAYMETHOD VALUES ('Kreditkarte');
INSERT INTO PAYMETHOD VALUES ('Nachnahme');
INSERT INTO PAYMETHOD VALUES ('Sofortueberweisung');
INSERT INTO PAYMETHOD VALUES ('Klarna');
INSERT INTO PAYMETHOD VALUES ('Giropay');
COMMIT;
